# Generated by Django 4.1.1 on 2022-09-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
