# Generated by Django 4.1.1 on 2022-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_author_alter_book_genre_alter_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='shop_book_created_5a3664_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated',
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['id', 'slug'], name='shop_author_id_db332e_idx'),
        ),
    ]
